///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sura___Claims
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Detalle_VehiculoAsegurado_Ocupantes recording.
    /// </summary>
    [TestModule("d16a476d-53f8-4662-9729-96eeec5a7393", ModuleType.Recording, 1)]
    public partial class Detalle_VehiculoAsegurado_Ocupantes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sura___ClaimsRepository repository.
        /// </summary>
        public static Sura___ClaimsRepository repo = Sura___ClaimsRepository.Instance;

        static Detalle_VehiculoAsegurado_Ocupantes instance = new Detalle_VehiculoAsegurado_Ocupantes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Detalle_VehiculoAsegurado_Ocupantes()
        {
            Gravedad = "Posible pérdida total";
            Descripcion = "Daño total por granizo";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Detalle_VehiculoAsegurado_Ocupantes Instance
        {
            get { return instance; }
        }

#region Variables

        string _Gravedad;

        /// <summary>
        /// Gets or sets the value of variable Gravedad.
        /// </summary>
        [TestVariable("a39c9a87-c219-4109-a5c1-fd3c585950d9")]
        public string Gravedad
        {
            get { return _Gravedad; }
            set { _Gravedad = value; }
        }

        string _Descripcion;

        /// <summary>
        /// Gets or sets the value of variable Descripcion.
        /// </summary>
        [TestVariable("8fe68be0-b0cb-4f30-8590-075ddc26c6c2")]
        public string Descripcion
        {
            get { return _Descripcion; }
            set { _Descripcion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("eacdab1b-b5fd-412e-9818-70d755718f78")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable DANIOS.
        /// </summary>
        [TestVariable("20c64a7e-189e-42ce-b6ca-314e3f69f001")]
        public string DANIOS
        {
            get { return repo.DANIOS; }
            set { repo.DANIOS = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable INCENDIO.
        /// </summary>
        [TestVariable("1e133474-0626-45f7-ad12-e7d4b399c501")]
        public string INCENDIO
        {
            get { return repo.INCENDIO; }
            set { repo.INCENDIO = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.tag_Vehiculo' at 21;8.", repo.SuraClaims.Motor.InformacionSiniestro.tag_VehiculoInfo, new RecordItemIndex(0));
            repo.SuraClaims.Motor.InformacionSiniestro.tag_Vehiculo.Click("21;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo.WaitForExists(30000);
            
            // Datos de conductor y acompañante
            Report.Log(ReportLevel.Info, "Section", "Datos de conductor y acompañante", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductor' at 46;4.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductorInfo, new RecordItemIndex(3));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductor.Click("46;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDeLosLesionados'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDeLosLesionadosInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDeLosLesionadosInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.picker_Personal' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.picker_PersonalInfo, new RecordItemIndex(5));
            repo.SuraClaims.Motor.InformacionSiniestro.picker_Personal.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.option_Nombre2' at 35;12.", repo.SuraClaims.Motor.option_Nombre2Info, new RecordItemIndex(6));
            repo.SuraClaims.Motor.option_Nombre2.Click("35;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_RelacionConPropietario_Asegurado'", repo.SuraClaims.Motor.InformacionSiniestro.txt_RelacionConPropietario_AseguradoInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_RelacionConPropietario_AseguradoInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_Aceptar' at 22;3.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AceptarInfo, new RecordItemIndex(8));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_Aceptar.Click("22;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new ActionTimeout(30000), new RecordItemIndex(9));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SuraClaims.Self, false, new RecordItemIndex(10));
            
            // Descripción del tipo de siniestro
            Report.Log(ReportLevel.Info, "Section", "Descripción del tipo de siniestro", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.lbl_DescripcionTipoSiniestro' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.lbl_DescripcionTipoSiniestroInfo, new RecordItemIndex(12));
            repo.SuraClaims.Motor.InformacionSiniestro.lbl_DescripcionTipoSiniestro.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_Danios'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DaniosInfo, new ActionTimeout(30000), new RecordItemIndex(13));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DaniosInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.cb_Danios' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.cb_DaniosInfo, new RecordItemIndex(14));
            repo.SuraClaims.Motor.InformacionSiniestro.cb_Danios.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_Gravedad'", repo.SuraClaims.Motor.InformacionSiniestro.txt_GravedadInfo, new ActionTimeout(30000), new RecordItemIndex(15));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_GravedadInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SuraClaims.Motor.InformacionSiniestro.txtbox_Gravedad'.", repo.SuraClaims.Motor.InformacionSiniestro.txtbox_GravedadInfo, new RecordItemIndex(16));
            Keyboard.PrepareFocus(repo.SuraClaims.Motor.InformacionSiniestro.txtbox_Gravedad);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Gravedad' with focus on 'SuraClaims.Motor.InformacionSiniestro.txtbox_Gravedad'.", repo.SuraClaims.Motor.InformacionSiniestro.txtbox_GravedadInfo, new RecordItemIndex(17));
            repo.SuraClaims.Motor.InformacionSiniestro.txtbox_Gravedad.PressKeys(Gravedad);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new RecordItemIndex(18));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionBasica.option_Nombre' at 26;9.", repo.SuraClaims.Motor.InformacionBasica.option_NombreInfo, new RecordItemIndex(19));
            //repo.SuraClaims.Motor.InformacionBasica.option_Nombre.Click("26;9");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.bttn_Agregar'", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarInfo, new ActionTimeout(30000), new RecordItemIndex(20));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_Agregar' at 18;6.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarInfo, new RecordItemIndex(21));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_Agregar.Click("18;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.tag_Descripcion' at 35;11.", repo.SuraClaims.Motor.InformacionSiniestro.tag_DescripcionInfo, new RecordItemIndex(22));
            repo.SuraClaims.Motor.InformacionSiniestro.tag_Descripcion.Click("35;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SuraClaims.Motor.InformacionSiniestro.tag_Descripcion'.", repo.SuraClaims.Motor.InformacionSiniestro.tag_DescripcionInfo, new RecordItemIndex(23));
            Keyboard.PrepareFocus(repo.SuraClaims.Motor.InformacionSiniestro.tag_Descripcion);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Descripcion' with focus on 'SuraClaims.Motor.InformacionSiniestro.tag_Descripcion'.", repo.SuraClaims.Motor.InformacionSiniestro.tag_DescripcionInfo, new RecordItemIndex(24));
            repo.SuraClaims.Motor.InformacionSiniestro.tag_Descripcion.PressKeys(Descripcion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new RecordItemIndex(25));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(26));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Daños ocasionados' with focus on 'SuraClaims.Motor.InformacionSiniestro.txtbox_DescripcionDeLosDanios'.", repo.SuraClaims.Motor.InformacionSiniestro.txtbox_DescripcionDeLosDaniosInfo, new RecordItemIndex(27));
            repo.SuraClaims.Motor.InformacionSiniestro.txtbox_DescripcionDeLosDanios.PressKeys("Daños ocasionados");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new RecordItemIndex(28));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.Copy_of_txtbox_DescripcionDeLosDanios'", repo.SuraClaims.Motor.InformacionSiniestro.Copy_of_txtbox_DescripcionDeLosDaniosInfo, new ActionTimeout(30000), new RecordItemIndex(29));
            repo.SuraClaims.Motor.InformacionSiniestro.Copy_of_txtbox_DescripcionDeLosDaniosInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.cb_Incendio' at 4;5.", repo.SuraClaims.Motor.InformacionSiniestro.cb_IncendioInfo, new RecordItemIndex(30));
            repo.SuraClaims.Motor.InformacionSiniestro.cb_Incendio.Click("4;5");
            Delay.Milliseconds(4620);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SuraClaims.Self, false, new RecordItemIndex(31));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_Aceptar' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AceptarInfo, new RecordItemIndex(32));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_Aceptar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Txt_Validaciones.txt_Paso3'", repo.SuraClaims.Txt_Validaciones.txt_Paso3Info, new ActionTimeout(30000), new RecordItemIndex(33));
            repo.SuraClaims.Txt_Validaciones.txt_Paso3Info.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
