///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sura___Claims
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Repository1 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("45cbbaf1-ef30-4c20-8e27-a9976826e1f8")]
    public partial class Repository1 : RepoGenBaseFolder
    {
        static Repository1 instance = new Repository1();
        Repository1Folders.GuidewireClaimCenterAppFolder _guidewireclaimcenter;

        /// <summary>
        /// Gets the singleton class instance representing the Repository1 element repository.
        /// </summary>
        [RepositoryFolder("45cbbaf1-ef30-4c20-8e27-a9976826e1f8")]
        public static Repository1 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Repository1() 
            : base("Repository1", "/", null, 0, false, "45cbbaf1-ef30-4c20-8e27-a9976826e1f8", ".\\RepositoryImages\\Repository145cbbaf1.rximgres")
        {
            _guidewireclaimcenter = new Repository1Folders.GuidewireClaimCenterAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("45cbbaf1-ef30-4c20-8e27-a9976826e1f8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The GuidewireClaimCenter folder.
        /// </summary>
        [RepositoryFolder("d0681cf0-6515-40c9-a9e6-1065890b9646")]
        public virtual Repository1Folders.GuidewireClaimCenterAppFolder GuidewireClaimCenter
        {
            get { return _guidewireclaimcenter; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Repository1Folders
    {
        /// <summary>
        /// The GuidewireClaimCenterAppFolder folder.
        /// </summary>
        [RepositoryFolder("d0681cf0-6515-40c9-a9e6-1065890b9646")]
        public partial class GuidewireClaimCenterAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _xformarrowtriggerxformarrowtriggeInfo;
            RepoItemInfo _galiciaInfo;

            /// <summary>
            /// Creates a new GuidewireClaimCenter  folder.
            /// </summary>
            public GuidewireClaimCenterAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GuidewireClaimCenter", "/dom[@domain='i-preproducciongestion.segurossura.com.ar']", parentFolder, 30000, null, false, "d0681cf0-6515-40c9-a9e6-1065890b9646", "")
            {
                _xformarrowtriggerxformarrowtriggeInfo = new RepoItemInfo(this, "XFormArrowTriggerXFormArrowTrigge", ".//tbody[#'centerPanel-tbody']/tr//table/tbody/tr[5]/td/div/div[2]/?/?/table//div/table//div/table/?/?/tr/td[1]/?/?/table/tbody/tr[9]/td/div/div/div/div[2]", 30000, null, "eb6045bf-052f-4221-8222-b7912c445c0d");
                _galiciaInfo = new RepoItemInfo(this, "GALICIA", "body/div[@id~'boundlist-']//ul/li[@id~'ext-element-' and @innertext~'[A-Z]+']", 30000, null, "bc13fea0-d392-49d0-9f0c-c3d84edc4082");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d0681cf0-6515-40c9-a9e6-1065890b9646")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d0681cf0-6515-40c9-a9e6-1065890b9646")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The XFormArrowTriggerXFormArrowTrigge item.
            /// </summary>
            [RepositoryItem("eb6045bf-052f-4221-8222-b7912c445c0d")]
            public virtual Ranorex.DivTag XFormArrowTriggerXFormArrowTrigge
            {
                get
                {
                    return _xformarrowtriggerxformarrowtriggeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The XFormArrowTriggerXFormArrowTrigge item info.
            /// </summary>
            [RepositoryItemInfo("eb6045bf-052f-4221-8222-b7912c445c0d")]
            public virtual RepoItemInfo XFormArrowTriggerXFormArrowTriggeInfo
            {
                get
                {
                    return _xformarrowtriggerxformarrowtriggeInfo;
                }
            }

            /// <summary>
            /// The GALICIA item.
            /// </summary>
            [RepositoryItem("bc13fea0-d392-49d0-9f0c-c3d84edc4082")]
            public virtual Ranorex.LiTag GALICIA
            {
                get
                {
                    return _galiciaInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The GALICIA item info.
            /// </summary>
            [RepositoryItemInfo("bc13fea0-d392-49d0-9f0c-c3d84edc4082")]
            public virtual RepoItemInfo GALICIAInfo
            {
                get
                {
                    return _galiciaInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
